variable "environment" {
  description = "Environment name (dev, test, prod)"
  type        = string
  default     = "dev"

  validation {
    condition     = contains(["dev", "test", "prod"], var.environment)
    error_message = "Environment must be one of: dev, test, prod."
  }
}

variable "location" {
  description = "Azure region for resources"
  type        = string
  default     = "West Europe"
}

variable "openai_api_key" {
  description = "OpenAI API Key"
  type        = string
  sensitive   = true
}

variable "azure_openai_endpoint" {
  description = "Azure OpenAI Endpoint (optional)"
  type        = string
  default     = ""
  sensitive   = true
}

variable "azure_openai_api_key" {
  description = "Azure OpenAI API Key (optional)"
  type        = string
  default     = ""
  sensitive   = true
}

variable "anthropic_api_key" {
  description = "Anthropic API Key (optional)"
  type        = string
  default     = ""
  sensitive   = true
}

variable "container_cpu" {
  description = "CPU cores for main container"
  type        = number
  default     = 1.0
}

variable "container_memory" {
  description = "Memory in GB for main container"
  type        = number
  default     = 2.0
}

variable "vnc_container_cpu" {
  description = "CPU cores for VNC browser container"
  type        = number
  default     = 0.5
}

variable "vnc_container_memory" {
  description = "Memory in GB for VNC browser container"
  type        = number
  default     = 1.0
}

variable "enable_vnc_browser" {
  description = "Enable VNC browser container"
  type        = bool
  default     = true
}

variable "vnc_password" {
  description = "Password for VNC access"
  type        = string
  default     = "magentic123!"
  sensitive   = true
}

variable "allowed_ip_ranges" {
  description = "List of IP ranges allowed to access the application"
  type        = list(string)
  default     = ["0.0.0.0/0"] # Change this to restrict access
}

variable "tags" {
  description = "Additional tags to apply to resources"
  type        = map(string)
  default     = {}
}

# Azure Developer CLI variables
variable "environmentName" {
  description = "Name of the azd environment"
  type        = string
  default     = "dev"
}

variable "resourceToken" {
  description = "Unique token for naming resources (auto-generated by azd)"
  type        = string
  default     = ""
}

variable "principalId" {
  description = "Principal ID of the user or service principal for role assignments"
  type        = string
  default     = ""
}
